---
dependency:
  name: galaxy
driver:
  name: delegated
platforms:
  - name: instance
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: ../../.venv/bin/python
      stdout_callback: yaml
verifier:
  name: ansible
