---
- name: Verify
  hosts: localhost
  tasks:
    - name: Assert that the files are created
      changed_when: false
      shell: 'cat /etc/ansible-role-openresty/{{ item }}'
      loop:
        - nginx.conf
        - conf.d/server.conf
        - conf.d/ssl.conf
        - conf.d/proxy.conf

    - stat:
        path: /etc/ansible-role-openresty/conf.d/remove
      register: remove_stat

    - name: Assert that other files are removed
      assert:
        that:
          - not remove_stat.stat.exists

    - stat:
        path: /etc/ansible-role-openresty/persist
      register: persist_stat

    - name: Assert that files outside of dir persist
      assert:
        that:
          - persist_stat.stat.exists

    - name: Assert that the temporary directory is removed
      register: tmp_files
      find:
        paths: '/tmp'
        patterns: 'ansible-role-openresty.*'
        use_regex: true
        file_type: 'directory'

    - name: Assert that tmp dir is removed
      changed_when: false
      assert:
        that:
          - tmp_files.files|length == 0
